Config                            = {}

Config.purple 				  = 11750815
Config.red 					  = 16711680
Config.blue 				  = 2061822
Config.green 				  = 56108
Config.orange 				  = 16744192
Config.grey 				  = 8421504
Config.darkred                = 10038562 
Config.ArmorValue = 98



-- Domyślne wszystko wyłączone | true = on | false = off |
Config = {
    TowTruckDrivers = {'S_M_M_TRUCKER_01', 'MP_M_WAREMECH_01', "a_c_pig","a_m_m_hillbilly_01"},
    NoClipTriggerCount = 3,
    Components = {
         AntiCheat = false,
         AntiSpectate = false,
         AntiTeleport = false,
         AntiNoclip = false,
         AntiSpeedhack = false
    },
    BlacklistedEvents = {
        "gcPhone:_internalAddMessageLRAC",
        "gcPhone:tchat_channelLRAC",
        "esx_vehicleshop:setVehicleOwnedLRAC",
        "esx_mafiajob:confiscateLRACPlayerItem",
        "_chat:messageEntLRACered",
        "lscustoms:pLRACayGarage",
        "vrp_slotmachLRACine:server:2",
        "Banca:dLRACeposit",
        "bank:depLRACositt",
        "esx_jobs:caLRACution", "give_back",
        "esx_fueldLRACelivery:pay",
        "esx_carthLRACief:pay",
        "esx_godiLRACrtyjob:pay",
        "esx_pizza:pLRACay",
        "esx_ranger:pLRACay",
        "esx_garbageLRACjob:pay",
        "esx_truckLRACerjob:pay",
        "AdminMeLRACnu:giveBank",
        "AdminMLRACenu:giveCash",
        "esx_goLRACpostaljob:pay",
        "esx_baLRACnksecurity:pay",
        "esx_sloLRACtmachine:sv:2",
        "esx:giLRACveInventoryItem",
        "NB:recLRACruterplayer",
        "esx_biLRAClling:sendBill",
        "esx_jailer:sendToJail",
        "esx_jaLRACil:sendToJail",
        "js:jaLRACiluser",
        "esx-qalle-jail:jailyer",
        "esx_dmvschool:pLRACay", 
        "LegacyFuel:PayFuLRACel",
        "OG_cuffs:cuffCheckNeLRACarest",
        "esx_policejob:handcuff",
        "cuffSeLRACrver",
        "cuffGLRACranted",
        "police:cuffGLRACranted",
        "esx_handcuffs:cufLRACfing",
        "esx_policejob:haLRACndcuff",
        "bank:withdLRACraw",
        "dmv:succeLRACss",
        "esx_skin:responseSaLRACveSkin",
        "esx_dmvschool:addLiceLRACnse",
        "esx_mechanicjob:starLRACtCraft",
        "esx_drugs:startHarvestWLRACeed",
        "esx_drugs:startTransfoLRACrmWeed",
        "esx_drugs:startSellWeLRACed",
        "esx_drugs:startHarvestLRACCoke",
        "esx_drugs:startTransLRACformCoke",
        "esx_drugs:startSellCLRACoke",
        "esx_drugs:startSellMLRACeth",
        "esx_drugs:startHLRACarvestOpium",
        "esx_drugs:startSellLRACOpium",
        "esx_drugs:starLRACtTransformOpium",
        "esx_blanchisLRACseur:startWhitening",
        "esx_drugs:stopHarvLRACestCoke",
        "esx_drugs:stopTranLRACsformCoke",
        "esx_drugs:stopSellLRACCoke",
        "esx_drugs:stopSellMLRACeth",
        "esx_drugs:stopHarLRACvestWeed",
        "esx_drugs:stopTLRACransformWeed",
        "esx_drugs:stopSellWLRACeed",
        "esx_drugs:stopHarvestLRACOpium",
        "esx_drugs:stopTransLRACformOpium",
        "esx_drugs:stopSellOpiuLRACm",
        "esx_society:openBosLRACsMenu",
        "esx_jobs:caLRACution",
        "esx_tankerjob:LRACpay",
        "esx_vehicletrunk:givLRACeDirty",
        "gambling:speLRACnd",
        "AdminMenu:giveDirtyMLRAConey",
        "esx_moneywash:depoLRACsit",
        "esx_moneywash:witLRAChdraw",
        "mission:completLRACed",
        "truckerJob:succeLRACss",
        "99kr-burglary:addMLRAConey",
        "esx_jailer:unjailTiLRACme",
        "esx_ambulancejob:reLRACvive",
        "DiscordBot:plaLRACyerDied",
        "hentailover:xdlol",
        "antiLRAC8:anticheat",
        "antiLRACr6:detection",
        "esx:getShLRACaredObjLRACect",
        "esx_society:getOnlLRACinePlayers",
        "antiLRAC8r4a:anticheat",
        "antiLRACr4:detect",
        "js:jaLRACiluser", 
        "ynx8:anticheat",
        "LRAC8:anticheat",
        "adminmenu:allowall",
        "ljail:jailplayer",
        "adminmenu:setsalary",
        "adminmenu:cashoutall",
        "bank:tranLRACsfer",
        "paycheck:bonLRACus",
        "paycheck:salLRACary",
        "HCheat:TempDisableDetLRACection",
        "esx_drugs:pickedUpCLRACannabis",
        "esx_drugs:processCLRACannabis",
        "esx-qalle-hunting:LRACreward",
        "esx-qalle-hunting:seLRACll",
        "esx_mecanojob:onNPCJobCLRACompleted",
        "BsCuff:Cuff696LRAC999",
        "veh_SR:CheckMonLRACeyForVeh",
        "esx_carthief:alertcoLRACps",
        "mellotrainer:adminTeLRACmpBan",
        "mellotrainer:adminKickLRAC",
        "esx_society:putVehicleLRACInGarage",
        "antilynx8:anticheat",
        "mellotrainer:adminKick",
        "esxjailer:sendToJail",
        "hentailover:xdlol",
        "Tem2LPs5Para5dCyjuHm87y2catFkMpV",
        "dqd36JWLRC72k8FDttZ5adUKwvwq9n9m",
        "antilynx8:anticheat",
        "antilynxr4:detect",
        "antilynxr6:detection",
        "ynx8:anticheat",
        "antilynx8r4a:anticheat",
        "lynx8:anticheat",
        "AntiLynxR4:kick",
        "AntiLynxR4:log",
        "h:xd"
    },

    BlacklistedWeapons = { -- Blacklista broni v2
    "WEAPON_APPISTOL",
    "WEAPON_DOUBLEACTION",
    "WEAPON_RAYPISTOL",
    "WEAPON_NAVYREVOLVER",
    "WEAPON_RAYCARBINE",
    "WEAPON_DBSHOTGUN",
    "WEAPON_AUTOSHOTGUN",
    "WEAPON_ASSAULTRIFLE",
    "WEAPON_MG",
    "WEAPON_HEAVYSNIPER",
    "WEAPON_FIREWORK",
    "WEAPON_HOMINGLAUNCHER",
    "WEAPON_COMPACTLAUNCHER",
    "WEAPON_RAYMINIGUN",
    "WEAPON_BZGAS",
    "WEAPON_MOLOTOV",
    "WEAPON_STICKYBOMB",
    "WEAPON_PROXMINE",
    "WEAPON_ADVANCEDRIFLE",
    "WEAPON_COMBATMG",
    "weapon_carbinerifle",
    "WEAPON_CARBINERIFLE_MK2",
    "WEAPON_ASSAULTSHOTGUN",
    "WEAPON_BULLPUPSHOTGUN",
    "WEAPON_GRENADELAUNCHER",
    "WEAPON_GRENADELAUNCHER_SMOKE",
    "WEAPON_RPG",
    "WEAPON_STINGER",
    "WEAPON_MINIGUN",
    "WEAPON_GRENADE",
    "WEAPON_GUSENBERG",
    "WEAPON_BULLPUPRIFLE",
    "WEAPON_DAGGER",
    "WEAPON_MUSKET",
    "WEAPON_HEAVYSHOTGUN",
    "WEAPON_MARKSMANRIFLE",
    "WEAPON_FLAREGUN",
    "WEAPON_GARBAGEBAG",
    "WEAPON_MARKSMANPISTOL",
    "WEAPON_HATCHET",
    "WEAPON_RAILGUN",
    "WEAPON_MACHINEPISTOL",
    "WEAPON_REVOLVER",
    "weapon_pistol50",
    "weapon_specialcarbine",
    "weapon_sniperrifle",
    "weapon_grenade"
  
      },




    BlacklistedModels = { -- Blacklista propy v2
        "rhino",
        "stt_prop_stunt_track_uturn",
        "stt_prop_stunt_track_turnice",
        "stt_prop_stunt_track_hill",
        "prop_gold_cont_01",
        "p_cablecar_s",
        "stt_prop_stunt_tube_l",
        "stt_prop_stunt_track_dwuturn",
        "prop_fnclink_05crnr1",
        "xs_prop_hamburgher_wl",
        "xs_prop_plastic_bottle_wl",
        "prop_container_05mb",
        "prop_windmill_01",
        "p_spinning_anus_s",
        "stt_prop_ramp_adj_flip_m",
        "prop_container_03a",
        "stt_prop_ramp_adj_flip_mb",
        "stt_prop_ramp_adj_flip_s",
        "stt_prop_ramp_adj_flip_sb", 
        "prop_container_05a",
        "stt_prop_ramp_adj_hloop",
        "stt_prop_ramp_adj_loop",
        "stt_prop_ramp_jump_l",
        "stt_prop_ramp_jump_m",
        "stt_prop_ramp_jump_s",
        "stt_prop_ramp_jump_xl",
        "stt_prop_ramp_jump_xs",
        "stt_prop_ramp_jump_xxl",
        "stt_prop_ramp_multi_loop_rb",
        "stt_prop_ramp_spiral_l",
        "stt_prop_ramp_spiral_l_l",
        "stt_prop_ramp_spiral_l_m",
        "stt_prop_ramp_spiral_l_s",
        "stt_prop_ramp_spiral_l_xxl",
        "prop_container_03b",
        "stt_prop_ramp_spiral_m",
        "stt_prop_ramp_spiral_s",
        "stt_prop_ramp_spiral_xxl",
        "stt_prop_stunt_track_dwslope30",
        "-145066854",
        "stt_prop_stunt_track_start",
        "stt_prop_stunt_track_slope45",
        "stt_prop_stunt_track_slope30",
        "stt_prop_stunt_track_slope15",
        "stt_prop_stunt_track_short",
        "stt_prop_stunt_track_sh45_a",
        "stt_prop_stunt_track_sh45",
        "stt_prop_stunt_track_sh30",
        "stt_prop_stunt_track_sh15",
        "stt_prop_stunt_track_otake",
        "stt_prop_stunt_track_link",
        "stt_prop_stunt_track_jump",
        "stt_prop_stunt_track_hill2",
        "stt_prop_stunt_track_hill",
        "stt_prop_stunt_track_funnel",
        "stt_prop_stunt_track_funlng",
        "stt_prop_stunt_track_fork",
        "stt_prop_stunt_track_exshort",
        "stt_prop_stunt_track_dwuturn",
        "stt_prop_stunt_track_dwturn",
        "stt_prop_stunt_track_dwslope45",
        "stt_prop_stunt_track_dwslope30",
        "stt_prop_stunt_track_dwslope15",
        "stt_prop_stunt_track_dwshort",
        "stt_prop_stunt_track_dwsh15",
        "stt_prop_stunt_track_dwlink_02",
        "stt_prop_stunt_track_dwlink",
        "stt_prop_stunt_track_cutout",
		"stt_prop_stunt_track_bumps",
        "stt_prop_stunt_target_small",
        "stt_prop_stunt_target",
        "stt_prop_stunt_soccer_sball",
        "stt_prop_stunt_soccer_lball",
        "stt_prop_stunt_soccer_goal",
        "stt_prop_stunt_soccer_ball",
        "hei_prop_carrier_cargo_02a",
        "stt_prop_stunt_ramp",
        "stt_prop_stunt_landing_zone_01",
        "stt_prop_stunt_jump_sb",
        "stt_prop_stunt_jump_s",
        "prop_container_ld2",
        "stt_prop_stunt_jump_mb",
        "hei_prop_carrier_cargo_02a", "p_cablecar_s", "p_ferris_car_01", "prop_cj_big_boat", "prop_rock_4_big2", "prop_steps_big_01", "v_ilev_lest_bigscreen", "prop_carcreeper", "apa_mp_h_bed_double_09", "apa_mp_h_bed_wide_05", "sanchez", "cargobob", "prop_cattlecrush", "prop_cs_documents_01", "a_c_cat_01", "prop_mp_spike_01", "prop_tyre_spike_01", "prop_container_ld2", "lts_prop_lts_ramp_03", "prop_jetski_ramp_01", "prop_mp_ramp_03_tu", "prop_skate_flatramp_cr", "stt_prop_ramp_adj_loop", "stt_prop_ramp_multi_loop_rb", "stt_prop_ramp_spiral_l", "stt_prop_ramp_spiral_l_m", "prop_const_fence03b_cr", "prop_const_fence02b", "prop_const_fence03a_cr", "prop_fnc_farm_01e", "prop_fnccorgm_02c", "ch3_01_dino", "p_pallet_02a_s", "prop_conc_blocks01a", "prop_consign_01a", "prop_byard_net02", "prop_mb_cargo_04b", "prop_mb_crate_01a_set", "prop_pipe_stack_01", "prop_roadcone01c", "prop_rub_cage01b", "prop_sign_road_01a", "prop_sign_road_03m", "prop_traffic_rail_2", "prop_traffic_rail_1a", "prop_traffic_03a", "prop_traffic_01d", "prop_skid_trolley_1", "hei_prop_yah_seat_03", "hei_prop_yah_table_03", "lts_prop_lts_elecbox_24", "lts_prop_lts_elecbox_24b", "p_airdancer_01_s", "p_amb_brolly_01", "p_amb_brolly_01_s", "p_dumpster_t", "p_ld_coffee_vend_01", "p_patio_lounger1_s", "p_yacht_sofa_01_s", "prop_air_bagloader2_cr", "prop_air_bigradar", "prop_air_blastfence_01", "prop_air_stair_01", "prop_air_sechut_01", "prop_airport_sale_sign",
        "stt_prop_stunt_jump_m",
        "stt_prop_stunt_jump_loop",
        "stt_prop_stunt_jump_lb",
        "stt_prop_stunt_jump_l",
        "stt_prop_stunt_jump45",
        "prop_container_04a",
        "stt_prop_stunt_jump30",
        "stt_prop_stunt_bowling_ball",
        "stt_prop_stunt_jump15",
        "stt_prop_stunt_domino",
        "prop_weed_pallet", "hei_prop_carrier_radar_1_l1", "v_res_mexball", "prop_rock_1_a", "prop_rock_1_b", "prop_rock_1_c", "prop_rock_1_d", "prop_player_gasmask", "prop_rock_1_e", "prop_rock_1_f", "prop_rock_1_g", "prop_rock_1_h", "prop_test_boulder_01", "prop_test_boulder_02", "prop_test_boulder_03", "prop_test_boulder_04", "apa_mp_apa_crashed_usaf_01a", "ex_prop_exec_crashdp", "apa_mp_apa_yacht_o1_rail_a", "apa_mp_apa_yacht_o1_rail_b", "apa_mp_h_yacht_armchair_01", "apa_mp_h_yacht_armchair_03", "apa_mp_h_yacht_armchair_04", "apa_mp_h_yacht_barstool_01", "apa_mp_h_yacht_bed_01", "apa_mp_h_yacht_bed_02", "apa_mp_h_yacht_coffee_table_01", "apa_mp_h_yacht_coffee_table_02", "apa_mp_h_yacht_floor_lamp_01", "apa_mp_h_yacht_side_table_01", "apa_mp_h_yacht_side_table_02", "apa_mp_h_yacht_sofa_01", "apa_mp_h_yacht_sofa_02", "apa_mp_h_yacht_stool_01", "apa_mp_h_yacht_strip_chair_01", "apa_mp_h_yacht_table_lamp_01", "apa_mp_h_yacht_table_lamp_02", "apa_mp_h_yacht_table_lamp_03", "prop_flag_columbia", "apa_mp_apa_yacht_o2_rail_a", "apa_mp_apa_yacht_o2_rail_b", "apa_mp_apa_yacht_o3_rail_a", "apa_mp_apa_yacht_o3_rail_b", "apa_mp_apa_yacht_option1", "proc_searock_01", "apa_mp_h_yacht_", "apa_mp_apa_yacht_option1_cola", "apa_mp_apa_yacht_option2", "apa_mp_apa_yacht_option2_cola", "apa_mp_apa_yacht_option2_colb", "apa_mp_apa_yacht_option3", "apa_mp_apa_yacht_option3_cola", "apa_mp_apa_yacht_option3_colb", "apa_mp_apa_yacht_option3_colc", "apa_mp_apa_yacht_option3_cold", "apa_mp_apa_yacht_option3_cole", "apa_mp_apa_yacht_jacuzzi_cam", "apa_mp_apa_yacht_jacuzzi_ripple003", "apa_mp_apa_yacht_jacuzzi_ripple1", "apa_mp_apa_yacht_jacuzzi_ripple2", "apa_mp_apa_yacht_radar_01a", "apa_mp_apa_yacht_win", "prop_crashed_heli", "apa_mp_apa_yacht_door", "prop_shamal_crash", "xm_prop_x17_shamal_crash", "apa_mp_apa_yacht_door2", "apa_mp_apa_yacht", "prop_flagpole_2b", "prop_flagpole_2c", "prop_flag_canada", "apa_prop_yacht_float_1a", "apa_prop_yacht_float_1b", "apa_prop_yacht_glass_01", "apa_prop_yacht_glass_02", "apa_prop_yacht_glass_03", "apa_prop_yacht_glass_04", "apa_prop_yacht_glass_05", "apa_prop_yacht_glass_06", "apa_prop_yacht_glass_07", "apa_prop_yacht_glass_08", "apa_prop_yacht_glass_09", "apa_prop_yacht_glass_10", "prop_flag_canada_s", "prop_flag_eu", "prop_flag_eu_s", "prop_target_blue_arrow", "prop_target_orange_arrow", "prop_target_purp_arrow", "prop_target_red_arrow", "apa_prop_flag_argentina", "apa_prop_flag_australia", "apa_prop_flag_austria", "apa_prop_flag_belgium", "apa_prop_flag_brazil", "apa_prop_flag_canadat_yt", "apa_prop_flag_china", "apa_prop_flag_columbia", "apa_prop_flag_croatia", "apa_prop_flag_czechrep", "apa_prop_flag_denmark", "apa_prop_flag_england", "apa_prop_flag_eu_yt", "apa_prop_flag_finland", "apa_prop_flag_france", "apa_prop_flag_german_yt", "apa_prop_flag_hungary", "apa_prop_flag_ireland", "apa_prop_flag_israel", "apa_prop_flag_italy", "apa_prop_flag_jamaica", "apa_prop_flag_japan_yt", "apa_prop_flag_canada_yt", "apa_prop_flag_lstein", "apa_prop_flag_malta", "apa_prop_flag_mexico_yt", "apa_prop_flag_netherlands", "apa_prop_flag_newzealand", "apa_prop_flag_nigeria", "apa_prop_flag_norway", "apa_prop_flag_palestine", "apa_prop_flag_poland", "apa_prop_flag_portugal", "apa_prop_flag_puertorico", "apa_prop_flag_russia_yt", "apa_prop_flag_scotland_yt", "apa_prop_flag_script", "apa_prop_flag_slovakia", "apa_prop_flag_slovenia", "apa_prop_flag_southafrica", "apa_prop_flag_southkorea", "apa_prop_flag_spain", "apa_prop_flag_sweden", "apa_prop_flag_switzerland", "apa_prop_flag_turkey", "apa_prop_flag_uk_yt", "apa_prop_flag_us_yt", "apa_prop_flag_wales", "prop_flag_uk", "prop_flag_uk_s", "prop_flag_us", "prop_flag_usboat", "prop_flag_us_r", "prop_flag_us_s", "prop_flag_france", "prop_flag_france_s", "prop_flag_german", "prop_flag_german_s", "prop_flag_ireland", "prop_flag_ireland_s", "prop_flag_japan", "prop_flag_japan_s", "prop_flag_ls", "prop_flag_lsfd", "prop_flag_lsfd_s", "prop_flag_lsservices", "prop_flag_lsservices_s", "prop_flag_ls_s", "prop_flag_mexico", "prop_flag_mexico_s", "prop_flag_russia", "prop_flag_russia_s", "prop_flag_s", "prop_flag_sa", "prop_flag_sapd", "prop_flag_sapd_s", "prop_flag_sa_s", "prop_flag_scotland", "prop_flag_scotland_s", "prop_flag_sheriff", "prop_flag_sheriff_s", "prop_flag_uk", "prop_flag_uk_s", "prop_flag_us", "prop_flag_usboat", "prop_flag_us_r", "prop_flag_us_s", "prop_flamingo", "prop_swiss_ball_01", "prop_air_bigradar_l1", "prop_air_bigradar_l2", "prop_air_bigradar_slod", "p_fib_rubble_s", "prop_money_bag_01", "p_cs_mp_jet_01_s", "prop_poly_bag_money", "prop_air_radar_01", "hei_prop_carrier_radar_1", "prop_air_bigradar", "prop_carrier_radar_1_l1", "prop_asteroid_01", "prop_xmas_ext", "p_oil_pjack_01_amo", "p_oil_pjack_01_s", "p_oil_pjack_02_amo", "p_oil_pjack_03_amo", "p_oil_pjack_02_s", "p_oil_pjack_03_s", "prop_aircon_l_03", "prop_med_jet_01", "p_med_jet_01_s", "hei_prop_carrier_jet", "bkr_prop_biker_bblock_huge_01", "bkr_prop_biker_bblock_huge_02", "bkr_prop_biker_bblock_huge_04", "bkr_prop_biker_bblock_huge_05", "hei_prop_heist_emp", "prop_weed_01", "prop_air_bigradar", "prop_juicestand", "prop_lev_des_barge_02", "hei_prop_carrier_defense_01", "prop_aircon_m_04", "prop_mp_ramp_03", "stt_prop_stunt_track_dwuturn", "ch3_12_animplane1_lod", "ch3_12_animplane2_lod", "hei_prop_hei_pic_pb_plane", "light_plane_rig", "prop_cs_plane_int_01", "prop_dummy_plane", "prop_mk_plane", "v_44_planeticket", "prop_planer_01", "ch3_03_cliffrocks03b_lod", "ch3_04_rock_lod_02", "csx_coastsmalrock_01_", "csx_coastsmalrock_02_", "csx_coastsmalrock_03_", "csx_coastsmalrock_04_", "mp_player_introck", "Heist_Yacht", "csx_coastsmalrock_05_", "mp_player_int_rock", "mp_player_introck", "prop_flagpole_1a", "prop_flagpole_2a", "prop_flagpole_3a", "prop_a4_pile_01", "cs2_10_sea_rocks_lod", "cs2_11_sea_marina_xr_rocks_03_lod", "prop_gold_cont_01", "prop_hydro_platform", "ch3_04_viewplatform_slod", "ch2_03c_rnchstones_lod", "proc_mntn_stone01", "prop_beachflag_le", "proc_mntn_stone02", "cs2_10_sea_shipwreck_lod", "des_shipsink_02", "prop_dock_shippad", "des_shipsink_03", "des_shipsink_04", "prop_mk_flag", "prop_mk_flag_2", "proc_mntn_stone03", "FreeModeMale01", "rsn_os_specialfloatymetal_n", "rsn_os_specialfloatymetal", "cs1_09_sea_ufo", "rsn_os_specialfloaty2_light2", "rsn_os_specialfloaty2_light", "rsn_os_specialfloaty2", "rsn_os_specialfloatymetal_n", "rsn_os_specialfloatymetal", "P_Spinning_Anus_S_Main", "P_Spinning_Anus_S_Root", "cs3_08b_rsn_db_aliencover_0001cs3_08b_rsn_db_aliencover_0001_a", "sc1_04_rnmo_paintoverlaysc1_04_rnmo_paintoverlay_a", "rnbj_wallsigns_0001", "proc_sml_stones01", "proc_sml_stones02", "maverick", "Miljet", "proc_sml_stones03", "proc_stones_01", "proc_stones_02", "proc_stones_03", "proc_stones_04", "proc_stones_05", "proc_stones_06", "prop_coral_stone_03", "prop_coral_stone_04", "prop_gravestones_01a", "prop_gravestones_02a", "prop_gravestones_03a", "prop_gravestones_04a", "prop_gravestones_05a", "prop_gravestones_06a", "prop_gravestones_07a", "prop_gravestones_08a", "prop_gravestones_09a", "prop_gravestones_10a", "prop_prlg_gravestone_05a_l1", "prop_prlg_gravestone_06a", "test_prop_gravestones_04a", "test_prop_gravestones_05a", "test_prop_gravestones_07a", "test_prop_gravestones_08a", "test_prop_gravestones_09a", "prop_prlg_gravestone_01a", "prop_prlg_gravestone_02a", "prop_prlg_gravestone_03a", "prop_prlg_gravestone_04a", "prop_stoneshroom1", "prop_stoneshroom2", "v_res_fa_stones01", "test_prop_gravestones_01a", "test_prop_gravestones_02a", "prop_prlg_gravestone_05a", "FreemodeFemale01", "p_cablecar_s", "stt_prop_stunt_tube_l", "stt_prop_stunt_track_dwuturn", "p_spinning_anus_s", "prop_windmill_01", "hei_prop_heist_tug", "prop_air_bigradar", "p_oil_slick_01", "prop_dummy_01", "hei_prop_heist_emp", "p_tram_cash_s", "hw1_blimp_ce2", "prop_fire_exting_1a", "prop_fire_exting_1b", "prop_fire_exting_2a", "prop_fire_exting_3a", "hw1_blimp_ce2_lod", "hw1_blimp_ce_lod", "hw1_blimp_cpr003", "hw1_blimp_cpr_null", "hw1_blimp_cpr_null2", "prop_lev_des_barage_02", "hei_prop_carrier_defense_01", "prop_juicestand", "S_M_M_MovAlien_01", "s_m_m_movalien_01", "s_m_m_movallien_01", "u_m_y_babyd", "CS_Orleans", "A_M_Y_ACult_01", "S_M_M_MovSpace_01", "U_M_Y_Zombie_01", "s_m_y_blackops_01", "a_f_y_topless_01", "a_c_boar", "a_c_cat_01", "a_c_chickenhawk", "a_c_chimp", "s_f_y_hooker_03", "a_c_chop", "a_c_cormorant", "a_c_cow", "a_c_coyote", "v_ilev_found_cranebucket", "p_cs_sub_hook_01_s", "a_c_crow", "a_c_dolphin", "a_c_fish", "hei_prop_heist_hook_01", "prop_rope_hook_01", "prop_sub_crane_hook", "s_f_y_hooker_01", "prop_vehicle_hook", "prop_v_hook_s", "prop_dock_crane_02_hook", "prop_winch_hook_long", "a_c_hen", "a_c_humpback", "a_c_husky", "a_c_killerwhale", "a_c_mtlion", "a_c_pigeon", "a_c_poodle", "prop_coathook_01", "prop_cs_sub_hook_01", "a_c_pug", "a_c_rabbit_01", "a_c_rat", "a_c_retriever", "a_c_rhesus", "a_c_rottweiler", "a_c_sharkhammer", "a_c_sharktiger", "a_c_shepherd", "a_c_stingray", "a_c_westy", "CS_Orleans", "prop_windmill_01", "prop_Ld_ferris_wheel", "p_tram_crash_s", "p_oil_slick_01",  "p_ld_soc_ball_01", "p_parachute1_s", "p_cablecar_s", "prop_beach_fire", "prop_lev_des_barge_02", "prop_lev_des_barge_01", "prop_sculpt_fix", "prop_flagpole_2b", "prop_flagpole_2c", "prop_winch_hook_short", "prop_flag_canada", "prop_flag_canada_s", "prop_flag_eu", "prop_flag_eu_s", "prop_flag_france", "prop_flag_france_s", "prop_flag_german", "prop_ld_hook", "prop_flag_german_s", "prop_flag_ireland", "prop_flag_ireland_s", "prop_flag_japan", "prop_flag_japan_s", "prop_flag_ls", "prop_flag_lsfd", "prop_flag_lsfd_s", "prop_cable_hook_01", "prop_flag_lsservices", "prop_flag_lsservices_s", "prop_flag_ls_s", "prop_flag_mexico", "prop_flag_mexico_s", "csx_coastboulder_00", "des_tankercrash_01", "des_tankerexplosion_01", "des_tankerexplosion_02", "des_trailerparka_02", "des_trailerparkb_02", "des_trailerparkc_02", "des_trailerparkd_02", "des_traincrash_root2", "des_traincrash_root3", "des_traincrash_root4", "des_traincrash_root5", "des_finale_vault_end", "des_finale_vault_root001", "des_finale_vault_root002", "des_finale_vault_root003", "des_finale_vault_root004", "des_finale_vault_start", "des_vaultdoor001_root001", "des_vaultdoor001_root002", "des_vaultdoor001_root003", "des_vaultdoor001_root004", "des_vaultdoor001_root005", "des_vaultdoor001_root006", "des_vaultdoor001_skin001", "des_vaultdoor001_start", "des_traincrash_root6", "prop_ld_vault_door", "prop_vault_door_scene", "prop_vault_door_scene", "prop_vault_shutter", "p_fin_vaultdoor_s", "prop_gold_vault_fence_l", "prop_gold_vault_fence_r", "prop_gold_vault_gate_01", "des_traincrash_root7", "prop_flag_russia", "prop_flag_russia_s", "prop_flag_s", "ch2_03c_props_rrlwindmill_lod", "prop_flag_sa", "prop_flag_sapd", "prop_flag_sapd_s", "prop_flag_sa_s", "prop_flag_scotland", "prop_flag_scotland_s", "prop_flag_sheriff", "prop_flag_sheriff_s", "prop_flag_uk", "prop_yacht_lounger", "prop_yacht_seat_01", "prop_yacht_seat_02", "prop_yacht_seat_03", "marina_xr_rocks_02", "marina_xr_rocks_03", "prop_test_rocks01", "prop_test_rocks02", "prop_test_rocks03", "prop_test_rocks04", "marina_xr_rocks_04", "marina_xr_rocks_05", "marina_xr_rocks_06", "prop_yacht_table_01", "csx_searocks_02", "csx_searocks_03", "csx_searocks_04", "csx_searocks_05", "csx_searocks_06", "p_yacht_chair_01_s", "p_yacht_sofa_01_s", "prop_yacht_table_02", "csx_coastboulder_00", "csx_coastboulder_01", "csx_coastboulder_02", "csx_coastboulder_03", "csx_coastboulder_04", "csx_coastboulder_05", "csx_coastboulder_06", "csx_coastboulder_07", "csx_coastrok1", "csx_coastrok2", "csx_coastrok3", "csx_coastrok4", "csx_coastsmalrock_01", "csx_coastsmalrock_02", "csx_coastsmalrock_03", "csx_coastsmalrock_04", "csx_coastsmalrock_05", "prop_yacht_table_03", "prop_flag_uk_s", "prop_flag_us", "prop_flag_usboat", "prop_flag_us_r", "prop_flag_us_s", "p_gasmask_s", "prop_flamingo", "plane", "jet", "cargoplane", "blimp", "blimp2", "blimp3"
    }
}

Config.Objects = {
    [GetHashKey("prop_container_05a")] = true, 
    [GetHashKey("prop_container_03b")] = true,
    [GetHashKey("prop_container_03a")] = true,
    [GetHashKey("prop_container_05mb")] = true,
    [GetHashKey("prop_container_04a")] = true,
    [GetHashKey("prop_container_ld2")] = true,
	[GetHashKey("hei_prop_carrier_radar_1_l1")] = true,
	[GetHashKey("v_res_mexball")] = true,
	[GetHashKey("prop_rock_1_a")] = true,
	[GetHashKey("prop_rock_1_b")] = true,
	[GetHashKey("prop_rock_1_c")] = true,
	[GetHashKey("prop_rock_1_d")] = true,
	[GetHashKey("prop_player_gasmask")] = true,
	[GetHashKey("prop_rock_1_e")] = true,
	[GetHashKey("prop_rock_1_f")] = true,
	[GetHashKey("prop_rock_1_g")] = true,
	[GetHashKey("prop_rock_1_h")] = true,
	[GetHashKey("prop_test_boulder_01")] = true,
	[GetHashKey("prop_test_boulder_02")] = true,
	[GetHashKey("prop_test_boulder_03")] = true,
	[GetHashKey("prop_test_boulder_04")] = true,
	[GetHashKey("apa_mp_apa_crashed_usaf_01a")] = true,
	[GetHashKey("ex_prop_exec_crashdp")] = true,
	[GetHashKey("apa_mp_apa_yacht_o1_rail_a")] = true,
	[GetHashKey("apa_mp_apa_yacht_o1_rail_b")] = true,
	[GetHashKey("apa_mp_h_yacht_armchair_01")] = true,
	[GetHashKey("apa_mp_h_yacht_armchair_03")] = true,
	[GetHashKey("apa_mp_h_yacht_armchair_04")] = true,
	[GetHashKey("apa_mp_h_yacht_barstool_01")] = true,
	[GetHashKey("apa_mp_h_yacht_bed_01")] = true,
	[GetHashKey("apa_mp_h_yacht_bed_02")] = true,
	[GetHashKey("apa_mp_h_yacht_coffee_table_01")] = true,
	[GetHashKey("apa_mp_h_yacht_coffee_table_02")] = true,
	[GetHashKey("apa_mp_h_yacht_floor_lamp_01")] = true,
	[GetHashKey("apa_mp_h_yacht_side_table_01")] = true,
	[GetHashKey("apa_mp_h_yacht_side_table_02")] = true,
	[GetHashKey("apa_mp_h_yacht_sofa_01")] = true,
	[GetHashKey("apa_mp_h_yacht_sofa_02")] = true,
	[GetHashKey("apa_mp_h_yacht_stool_01")] = true,
	[GetHashKey("apa_mp_h_yacht_strip_chair_01")] = true,
	[GetHashKey("apa_mp_h_yacht_table_lamp_01")] = true,
	[GetHashKey("apa_mp_h_yacht_table_lamp_02")] = true,
	[GetHashKey("apa_mp_h_yacht_table_lamp_03")] = true,
	[GetHashKey("prop_flag_columbia")] = true,
	[GetHashKey("apa_mp_apa_yacht_o2_rail_a")] = true,
	[GetHashKey("apa_mp_apa_yacht_o2_rail_b")] = true,
	[GetHashKey("apa_mp_apa_yacht_o3_rail_a")] = true,
	[GetHashKey("apa_mp_apa_yacht_o3_rail_b")] = true,
	[GetHashKey("apa_mp_apa_yacht_option1")] = true,
	[GetHashKey("proc_searock_01")] = true,
	[GetHashKey("apa_mp_h_yacht_")] = true,
	[GetHashKey("apa_mp_apa_yacht_option1_cola")] = true,
	[GetHashKey("apa_mp_apa_yacht_option2")] = true,
	[GetHashKey("apa_mp_apa_yacht_option2_cola")] = true,
	[GetHashKey("apa_mp_apa_yacht_option2_colb")] = true,
	[GetHashKey("apa_mp_apa_yacht_option3")] = true,
	[GetHashKey("apa_mp_apa_yacht_option3_cola")] = true,
	[GetHashKey("apa_mp_apa_yacht_option3_colb")] = true,
	[GetHashKey("apa_mp_apa_yacht_option3_colc")] = true,
	[GetHashKey("apa_mp_apa_yacht_option3_cold")] = true,
	[GetHashKey("apa_mp_apa_yacht_option3_cole")] = true,
	[GetHashKey("apa_mp_apa_yacht_jacuzzi_cam")] = true,
	[GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple003")] = true,
	[GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple1")] = true,
	[GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple2")] = true,
	[GetHashKey("apa_mp_apa_yacht_radar_01a")] = true,
	[GetHashKey("apa_mp_apa_yacht_win")] = true,
	[GetHashKey("prop_crashed_heli")] = true,
	[GetHashKey("apa_mp_apa_yacht_door")] = true,
	[GetHashKey("prop_shamal_crash")] = true,
	[GetHashKey("xm_prop_x17_shamal_crash")] = true,
	[GetHashKey("apa_mp_apa_yacht_door2")] = true,
	[GetHashKey("apa_mp_apa_yacht")] = true,
	[GetHashKey("prop_flagpole_2b")] = true,
	[GetHashKey("prop_flagpole_2c")] = true,
	[GetHashKey("prop_flag_canada")] = true,
	[GetHashKey("apa_prop_yacht_float_1a")] = true,
	[GetHashKey("apa_prop_yacht_float_1b")] = true,
	[GetHashKey("apa_prop_yacht_glass_01")] = true,
	[GetHashKey("apa_prop_yacht_glass_02")] = true,
	[GetHashKey("apa_prop_yacht_glass_03")] = true,
	[GetHashKey("apa_prop_yacht_glass_04")] = true,
	[GetHashKey("apa_prop_yacht_glass_05")] = true,
	[GetHashKey("apa_prop_yacht_glass_06")] = true,
	[GetHashKey("apa_prop_yacht_glass_07")] = true,
	[GetHashKey("apa_prop_yacht_glass_08")] = true,
	[GetHashKey("apa_prop_yacht_glass_09")] = true,
	[GetHashKey("apa_prop_yacht_glass_10")] = true,
	[GetHashKey("prop_flag_canada_s")] = true,
	[GetHashKey("prop_flag_eu")] = true,
	[GetHashKey("prop_flag_eu_s")] = true,
	[GetHashKey("prop_target_blue_arrow")] = true,
	[GetHashKey("prop_target_orange_arrow")] = true,
	[GetHashKey("prop_target_purp_arrow")] = true,
	[GetHashKey("prop_target_red_arrow")] = true,
	[GetHashKey("apa_prop_flag_argentina")] = true,
	[GetHashKey("apa_prop_flag_australia")] = true,
	[GetHashKey("apa_prop_flag_austria")] = true,
	[GetHashKey("apa_prop_flag_belgium")] = true,
	[GetHashKey("apa_prop_flag_brazil")] = true,
	[GetHashKey("apa_prop_flag_canadat_yt")] = true,
	[GetHashKey("apa_prop_flag_china")] = true,
	[GetHashKey("apa_prop_flag_columbia")] = true,
	[GetHashKey("apa_prop_flag_croatia")] = true,
	[GetHashKey("apa_prop_flag_czechrep")] = true,
	[GetHashKey("apa_prop_flag_denmark")] = true,
	[GetHashKey("apa_prop_flag_england")] = true,
	[GetHashKey("apa_prop_flag_eu_yt")] = true,
	[GetHashKey("apa_prop_flag_finland")] = true,
	[GetHashKey("apa_prop_flag_france")] = true,
	[GetHashKey("apa_prop_flag_german_yt")] = true,
	[GetHashKey("apa_prop_flag_hungary")] = true,
	[GetHashKey("apa_prop_flag_ireland")] = true,
	[GetHashKey("apa_prop_flag_israel")] = true,
	[GetHashKey("apa_prop_flag_italy")] = true,
	[GetHashKey("apa_prop_flag_jamaica")] = true,
	[GetHashKey("apa_prop_flag_japan_yt")] = true,
	[GetHashKey("apa_prop_flag_canada_yt")] = true,
	[GetHashKey("apa_prop_flag_lstein")] = true,
	[GetHashKey("apa_prop_flag_malta")] = true,
	[GetHashKey("apa_prop_flag_mexico_yt")] = true,
	[GetHashKey("apa_prop_flag_netherlands")] = true,
	[GetHashKey("apa_prop_flag_newzealand")] = true,
	[GetHashKey("apa_prop_flag_nigeria")] = true,
	[GetHashKey("apa_prop_flag_norway")] = true,
	[GetHashKey("apa_prop_flag_palestine")] = true,
	[GetHashKey("apa_prop_flag_poland")] = true,
	[GetHashKey("apa_prop_flag_portugal")] = true,
	[GetHashKey("apa_prop_flag_puertorico")] = true,
	[GetHashKey("apa_prop_flag_russia_yt")] = true,
	[GetHashKey("apa_prop_flag_scotland_yt")] = true,
	[GetHashKey("apa_prop_flag_script")] = true,
	[GetHashKey("apa_prop_flag_slovakia")] = true,
	[GetHashKey("apa_prop_flag_slovenia")] = true,
	[GetHashKey("apa_prop_flag_southafrica")] = true,
	[GetHashKey("apa_prop_flag_southkorea")] = true,
	[GetHashKey("apa_prop_flag_spain")] = true,
	[GetHashKey("apa_prop_flag_sweden")] = true,
	[GetHashKey("apa_prop_flag_switzerland")] = true,
	[GetHashKey("apa_prop_flag_turkey")] = true,
	[GetHashKey("apa_prop_flag_uk_yt")] = true,
	[GetHashKey("apa_prop_flag_us_yt")] = true,
	[GetHashKey("apa_prop_flag_wales")] = true,
	[GetHashKey("prop_flag_uk")] = true,
	[GetHashKey("prop_flag_uk_s")] = true,
	[GetHashKey("prop_flag_us")] = true,
	[GetHashKey("prop_flag_usboat")] = true,
	[GetHashKey("prop_flag_us_r")] = true,
	[GetHashKey("prop_flag_us_s")] = true,
	[GetHashKey("prop_flag_france")] = true,
	[GetHashKey("prop_flag_france_s")] = true,
	[GetHashKey("prop_flag_german")] = true,
	[GetHashKey("prop_flag_german_s")] = true,
	[GetHashKey("prop_flag_ireland")] = true,
	[GetHashKey("prop_flag_ireland_s")] = true,
	[GetHashKey("prop_flag_japan")] = true,
	[GetHashKey("prop_flag_japan_s")] = true,
	[GetHashKey("prop_flag_ls")] = true,
	[GetHashKey("prop_flag_lsfd")] = true,
	[GetHashKey("prop_flag_lsfd_s")] = true,
	[GetHashKey("prop_flag_lsservices")] = true,
	[GetHashKey("prop_flag_lsservices_s")] = true,
	[GetHashKey("prop_flag_ls_s")] = true,
	[GetHashKey("prop_flag_mexico")] = true,
	[GetHashKey("prop_flag_mexico_s")] = true,
	[GetHashKey("prop_flag_russia")] = true,
	[GetHashKey("prop_flag_russia_s")] = true,
	[GetHashKey("prop_flag_s")] = true,
	[GetHashKey("prop_flag_sa")] = true,
	[GetHashKey("prop_flag_sapd")] = true,
	[GetHashKey("prop_flag_sapd_s")] = true,
	[GetHashKey("prop_flag_sa_s")] = true,
	[GetHashKey("prop_flag_scotland")] = true,
	[GetHashKey("prop_flag_scotland_s")] = true,
	[GetHashKey("prop_flag_sheriff")] = true,
	[GetHashKey("prop_flag_sheriff_s")] = true,
	[GetHashKey("prop_flag_uk")] = true,
	[GetHashKey("prop_flag_uk_s")] = true,
	[GetHashKey("prop_flag_us")] = true,
	[GetHashKey("prop_flag_usboat")] = true,
	[GetHashKey("prop_flag_us_r")] = true,
	[GetHashKey("prop_flag_us_s")] = true,
	[GetHashKey("prop_flamingo")] = true,
	[GetHashKey("prop_swiss_ball_01")] = true,
	[GetHashKey("prop_air_bigradar_l1")] = true,
	[GetHashKey("prop_air_bigradar_l2")] = true,
	[GetHashKey("prop_air_bigradar_slod")] = true,
	[GetHashKey("p_fib_rubble_s")] = true,
	[GetHashKey("prop_money_bag_01")] = true,
	[GetHashKey("p_cs_mp_jet_01_s")] = true,
	[GetHashKey("prop_poly_bag_money")] = true,
	[GetHashKey("prop_air_radar_01")] = true,
	[GetHashKey("hei_prop_carrier_radar_1")] = true,
	[GetHashKey("prop_air_bigradar")] = true,
	[GetHashKey("prop_carrier_radar_1_l1")] = true,
	[GetHashKey("prop_asteroid_01")] = true,
	[GetHashKey("prop_xmas_ext")] = true,
	[GetHashKey("p_oil_pjack_01_amo")] = true,
	[GetHashKey("p_oil_pjack_01_s")] = true,
	[GetHashKey("p_oil_pjack_02_amo")] = true,
	[GetHashKey("p_oil_pjack_03_amo")] = true,
	[GetHashKey("p_oil_pjack_02_s")] = true,
	[GetHashKey("p_oil_pjack_03_s")] = true,
	[GetHashKey("prop_aircon_l_03")] = true,
	[GetHashKey("prop_med_jet_01")] = true,
	[GetHashKey("p_med_jet_01_s")] = true,
	[GetHashKey("hei_prop_carrier_jet")] = true,
	[GetHashKey("bkr_prop_biker_bblock_huge_01")] = true,
	[GetHashKey("bkr_prop_biker_bblock_huge_02")] = true,
	[GetHashKey("bkr_prop_biker_bblock_huge_04")] = true,
	[GetHashKey("bkr_prop_biker_bblock_huge_05")] = true,
	[GetHashKey("hei_prop_heist_emp")] = true,
	[GetHashKey("prop_weed_01")] = true,
	[GetHashKey("prop_air_bigradar")] = true,
	[GetHashKey("prop_juicestand")] = true,
	[GetHashKey("prop_lev_des_barge_02")] = true,
	[GetHashKey("hei_prop_carrier_defense_01")] = true,
	[GetHashKey("prop_aircon_m_04")] = true,
	[GetHashKey("prop_mp_ramp_03")] = true,
	[GetHashKey("stt_prop_stunt_track_dwuturn")] = true,
	[GetHashKey("ch3_12_animplane1_lod")] = true,
	[GetHashKey("ch3_12_animplane2_lod")] = true,
	[GetHashKey("hei_prop_hei_pic_pb_plane")] = true,
	[GetHashKey("light_plane_rig")] = true,
	[GetHashKey("prop_cs_plane_int_01")] = true,
	[GetHashKey("prop_dummy_plane")] = true,
	[GetHashKey("prop_mk_plane")] = true,
	[GetHashKey("v_44_planeticket")] = true,
	[GetHashKey("prop_planer_01")] = true,
	[GetHashKey("ch3_03_cliffrocks03b_lod")] = true,
	[GetHashKey("ch3_04_rock_lod_02")] = true,
	[GetHashKey("csx_coastsmalrock_01_")] = true,
	[GetHashKey("csx_coastsmalrock_02_")] = true,
	[GetHashKey("csx_coastsmalrock_03_")] = true,
	[GetHashKey("csx_coastsmalrock_04_")] = true,
	[GetHashKey("mp_player_introck")] = true,
	[GetHashKey("Heist_Yacht")] = true,
	[GetHashKey("csx_coastsmalrock_05_")] = true,
	[GetHashKey("mp_player_int_rock")] = true,
	[GetHashKey("mp_player_introck")] = true,
	[GetHashKey("prop_flagpole_1a")] = true,
	[GetHashKey("prop_flagpole_2a")] = true,
	[GetHashKey("prop_flagpole_3a")] = true,
	[GetHashKey("prop_a4_pile_01")] = true,
	[GetHashKey("cs2_10_sea_rocks_lod")] = true,
	[GetHashKey("cs2_11_sea_marina_xr_rocks_03_lod")] = true,
	[GetHashKey("prop_gold_cont_01")] = true,
	[GetHashKey("prop_hydro_platform")] = true,
	[GetHashKey("ch3_04_viewplatform_slod")] = true,
	[GetHashKey("ch2_03c_rnchstones_lod")] = true,
	[GetHashKey("proc_mntn_stone01")] = true,
	[GetHashKey("prop_beachflag_le")] = true,
	[GetHashKey("proc_mntn_stone02")] = true,
	[GetHashKey("cs2_10_sea_shipwreck_lod")] = true,
	[GetHashKey("des_shipsink_02")] = true,
	[GetHashKey("prop_dock_shippad")] = true,
	[GetHashKey("des_shipsink_03")] = true,
	[GetHashKey("des_shipsink_04")] = true,
	[GetHashKey("prop_mk_flag")] = true,
	[GetHashKey("prop_mk_flag_2")] = true,
	[GetHashKey("proc_mntn_stone03")] = true,
	[GetHashKey("FreeModeMale01")] = true,
	[GetHashKey("rsn_os_specialfloatymetal_n")] = true,
	[GetHashKey("rsn_os_specialfloatymetal")] = true,
	[GetHashKey("cs1_09_sea_ufo")] = true,
	[GetHashKey("rsn_os_specialfloaty2_light2")] = true,
	[GetHashKey("rsn_os_specialfloaty2_light")] = true,
	[GetHashKey("rsn_os_specialfloaty2")] = true,
	[GetHashKey("rsn_os_specialfloatymetal_n")] = true,
	[GetHashKey("rsn_os_specialfloatymetal")] = true,
	[GetHashKey("P_Spinning_Anus_S_Main")] = true,
	[GetHashKey("P_Spinning_Anus_S_Root")] = true,
	[GetHashKey("cs3_08b_rsn_db_aliencover_0001cs3_08b_rsn_db_aliencover_0001_a")] = true,
	[GetHashKey("sc1_04_rnmo_paintoverlaysc1_04_rnmo_paintoverlay_a")] = true,
	[GetHashKey("rnbj_wallsigns_0001")] = true,
	[GetHashKey("proc_sml_stones01")] = true,
	[GetHashKey("proc_sml_stones02")] = true,
	[GetHashKey("maverick")] = true,
	[GetHashKey("Miljet")] = true,
	[GetHashKey("proc_sml_stones03")] = true,
	[GetHashKey("proc_stones_01")] = true,
	[GetHashKey("proc_stones_02")] = true,
	[GetHashKey("proc_stones_03")] = true,
	[GetHashKey("proc_stones_04")] = true,
	[GetHashKey("proc_stones_05")] = true,
	[GetHashKey("proc_stones_06")] = true,
	[GetHashKey("prop_coral_stone_03")] = true,
	[GetHashKey("prop_coral_stone_04")] = true,
	[GetHashKey("prop_gravestones_01a")] = true,
	[GetHashKey("prop_gravestones_02a")] = true,
	[GetHashKey("prop_gravestones_03a")] = true,
	[GetHashKey("prop_gravestones_04a")] = true,
	[GetHashKey("prop_gravestones_05a")] = true,
	[GetHashKey("prop_gravestones_06a")] = true,
	[GetHashKey("prop_gravestones_07a")] = true,
	[GetHashKey("prop_gravestones_08a")] = true,
	[GetHashKey("prop_gravestones_09a")] = true,
	[GetHashKey("prop_gravestones_10a")] = true,
	[GetHashKey("prop_prlg_gravestone_05a_l1")] = true,
	[GetHashKey("prop_prlg_gravestone_06a")] = true,
	[GetHashKey("test_prop_gravestones_04a")] = true,
	[GetHashKey("test_prop_gravestones_05a")] = true,
	[GetHashKey("test_prop_gravestones_07a")] = true,
	[GetHashKey("test_prop_gravestones_08a")] = true,
	[GetHashKey("test_prop_gravestones_09a")] = true,
	[GetHashKey("prop_prlg_gravestone_01a")] = true,
	[GetHashKey("prop_prlg_gravestone_02a")] = true,
	[GetHashKey("prop_prlg_gravestone_03a")] = true,
	[GetHashKey("prop_prlg_gravestone_04a")] = true,
	[GetHashKey("prop_stoneshroom1")] = true,
	[GetHashKey("prop_stoneshroom2")] = true,
	[GetHashKey("v_res_fa_stones01")] = true,
	[GetHashKey("test_prop_gravestones_01a")] = true,
	[GetHashKey("test_prop_gravestones_02a")] = true,
	[GetHashKey("prop_prlg_gravestone_05a")] = true,
	[GetHashKey("FreemodeFemale01")] = true,
	[GetHashKey("p_cablecar_s")] = true,
	[GetHashKey("stt_prop_stunt_tube_l")] = true,
	[GetHashKey("stt_prop_stunt_track_dwuturn")] = true,
	[GetHashKey("p_spinning_anus_s")] = true,
	[GetHashKey("prop_windmill_01")] = true,
	[GetHashKey("hei_prop_heist_tug")] = true,
	[GetHashKey("prop_air_bigradar")] = true,
	[GetHashKey("p_oil_slick_01")] = true,
	[GetHashKey("prop_dummy_01")] = true,
	[GetHashKey("hei_prop_heist_emp")] = true,
	[GetHashKey("p_tram_cash_s")] = true,
	[GetHashKey("hw1_blimp_ce2")] = true,
	[GetHashKey("prop_fire_exting_1a")] = true,
	[GetHashKey("prop_fire_exting_1b")] = true,
	[GetHashKey("prop_fire_exting_2a")] = true,
	[GetHashKey("prop_fire_exting_3a")] = true,
	[GetHashKey("hw1_blimp_ce2_lod")] = true,
	[GetHashKey("hw1_blimp_ce_lod")] = true,
	[GetHashKey("hw1_blimp_cpr003")] = true,
	[GetHashKey("hw1_blimp_cpr_null")] = true,
	[GetHashKey("hw1_blimp_cpr_null2")] = true,
	[GetHashKey("prop_lev_des_barage_02")] = true,
	[GetHashKey("hei_prop_carrier_defense_01")] = true,
	[GetHashKey("prop_juicestand")] = true,
	[GetHashKey("S_M_M_MovAlien_01")] = true,
	[GetHashKey("s_m_m_movalien_01")] = true,
	[GetHashKey("s_m_m_movallien_01")] = true,
	[GetHashKey("u_m_y_babyd")] = true,
	[GetHashKey("CS_Orleans")] = true,
	[GetHashKey("A_M_Y_ACult_01")] = true,
	[GetHashKey("S_M_M_MovSpace_01")] = true,
	[GetHashKey("U_M_Y_Zombie_01")] = true,
	[GetHashKey("s_m_y_blackops_01")] = true,
	[GetHashKey("a_f_y_topless_01")] = true,
	[GetHashKey("a_c_boar")] = true,
	[GetHashKey("a_c_cat_01")] = true,
	[GetHashKey("a_c_chickenhawk")] = true,
	[GetHashKey("a_c_chimp")] = true,
	[GetHashKey("s_f_y_hooker_03")] = true,
	[GetHashKey("a_c_chop")] = true,
	[GetHashKey("a_c_cormorant")] = true,
	[GetHashKey("a_c_cow")] = true,
	[GetHashKey("a_c_coyote")] = true,
	[GetHashKey("v_ilev_found_cranebucket")] = true,
	[GetHashKey("p_cs_sub_hook_01_s")] = true,
	[GetHashKey("a_c_crow")] = true,
	[GetHashKey("a_c_dolphin")] = true,
	[GetHashKey("a_c_fish")] = true,
	[GetHashKey("hei_prop_heist_hook_01")] = true,
	[GetHashKey("prop_rope_hook_01")] = true,
	[GetHashKey("prop_sub_crane_hook")] = true,
	[GetHashKey("s_f_y_hooker_01")] = true,
	[GetHashKey("prop_vehicle_hook")] = true,
	[GetHashKey("prop_v_hook_s")] = true,
	[GetHashKey("prop_dock_crane_02_hook")] = true,
	[GetHashKey("prop_winch_hook_long")] = true,
	[GetHashKey("a_c_hen")] = true,
	[GetHashKey("a_c_humpback")] = true,
	[GetHashKey("a_c_husky")] = true,
	[GetHashKey("a_c_killerwhale")] = true,
	[GetHashKey("a_c_mtlion")] = true,
	[GetHashKey("a_c_pigeon")] = true,
	[GetHashKey("a_c_poodle")] = true,
	[GetHashKey("prop_coathook_01")] = true,
	[GetHashKey("prop_cs_sub_hook_01")] = true,
	[GetHashKey("a_c_pug")] = true,
	[GetHashKey("a_c_rabbit_01")] = true,
	[GetHashKey("a_c_rat")] = true,
	[GetHashKey("a_c_retriever")] = true,
	[GetHashKey("a_c_rhesus")] = true,
	[GetHashKey("a_c_rottweiler")] = true,
	[GetHashKey("a_c_sharkhammer")] = true,
	[GetHashKey("a_c_sharktiger")] = true,
	[GetHashKey("a_c_shepherd")] = true,
	[GetHashKey("a_c_stingray")] = true,
	[GetHashKey("a_c_westy")] = true,
	[GetHashKey("CS_Orleans")] = true,
	[GetHashKey("prop_windmill_01")] = true,
	[GetHashKey("prop_Ld_ferris_wheel")] = true,
	[GetHashKey("p_tram_crash_s")] = true,
	[GetHashKey("p_oil_slick_01")] = true,
	[GetHashKey("p_ld_stinger_s")] = true,
	[GetHashKey("p_ld_soc_ball_01")] = true,
	[GetHashKey("p_parachute1_s")] = true,
	[GetHashKey("p_cablecar_s")] = true,
	[GetHashKey("prop_beach_fire")] = true,
	[GetHashKey("prop_lev_des_barge_02")] = true,
	[GetHashKey("prop_lev_des_barge_01")] = true,
	[GetHashKey("prop_sculpt_fix")] = true,
	[GetHashKey("prop_flagpole_2b")] = true,
	[GetHashKey("prop_flagpole_2c")] = true,
	[GetHashKey("prop_winch_hook_short")] = true,
	[GetHashKey("prop_flag_canada")] = true,
	[GetHashKey("prop_flag_canada_s")] = true,
	[GetHashKey("prop_flag_eu")] = true,
	[GetHashKey("prop_flag_eu_s")] = true,
	[GetHashKey("prop_flag_france")] = true,
	[GetHashKey("prop_flag_france_s")] = true,
	[GetHashKey("prop_flag_german")] = true,
	[GetHashKey("prop_ld_hook")] = true,
	[GetHashKey("prop_flag_german_s")] = true,
	[GetHashKey("prop_flag_ireland")] = true,
	[GetHashKey("prop_flag_ireland_s")] = true,
	[GetHashKey("prop_flag_japan")] = true,
	[GetHashKey("prop_flag_japan_s")] = true,
	[GetHashKey("prop_flag_ls")] = true,
	[GetHashKey("prop_flag_lsfd")] = true,
	[GetHashKey("prop_flag_lsfd_s")] = true,
	[GetHashKey("prop_cable_hook_01")] = true,
	[GetHashKey("prop_flag_lsservices")] = true,
	[GetHashKey("prop_flag_lsservices_s")] = true,
	[GetHashKey("prop_flag_ls_s")] = true,
	[GetHashKey("prop_flag_mexico")] = true,
	[GetHashKey("prop_flag_mexico_s")] = true,
	[GetHashKey("csx_coastboulder_00")] = true,
	[GetHashKey("des_tankercrash_01")] = true,
	[GetHashKey("des_tankerexplosion_01")] = true,
	[GetHashKey("des_tankerexplosion_02")] = true,
	[GetHashKey("des_trailerparka_02")] = true,
	[GetHashKey("des_trailerparkb_02")] = true,
	[GetHashKey("des_trailerparkc_02")] = true,
	[GetHashKey("des_trailerparkd_02")] = true,
	[GetHashKey("des_traincrash_root2")] = true,
	[GetHashKey("des_traincrash_root3")] = true,
	[GetHashKey("des_traincrash_root4")] = true,
	[GetHashKey("des_traincrash_root5")] = true,
	[GetHashKey("des_finale_vault_end")] = true,
	[GetHashKey("des_finale_vault_root001")] = true,
	[GetHashKey("des_finale_vault_root002")] = true,
	[GetHashKey("des_finale_vault_root003")] = true,
	[GetHashKey("des_finale_vault_root004")] = true,
	[GetHashKey("des_finale_vault_start")] = true,
	[GetHashKey("des_vaultdoor001_root001")] = true,
	[GetHashKey("des_vaultdoor001_root002")] = true,
	[GetHashKey("des_vaultdoor001_root003")] = true,
	[GetHashKey("des_vaultdoor001_root004")] = true,
	[GetHashKey("des_vaultdoor001_root005")] = true,
	[GetHashKey("des_vaultdoor001_root006")] = true,
	[GetHashKey("des_vaultdoor001_skin001")] = true,
	[GetHashKey("des_vaultdoor001_start")] = true,
	[GetHashKey("des_traincrash_root6")] = true,
	[GetHashKey("prop_ld_vault_door")] = true,
	[GetHashKey("prop_vault_door_scene")] = true,
	[GetHashKey("prop_vault_door_scene")] = true,
	[GetHashKey("prop_vault_shutter")] = true,
	[GetHashKey("p_fin_vaultdoor_s")] = true,
	[GetHashKey("v_ilev_bk_vaultdoor")] = true,
	[GetHashKey("prop_gold_vault_fence_l")] = true,
	[GetHashKey("prop_gold_vault_fence_r")] = true,
	[GetHashKey("prop_gold_vault_gate_01")] = true,
	[GetHashKey("prop_bank_vaultdoor")] = true,
	[GetHashKey("des_traincrash_root7")] = true,
	[GetHashKey("prop_flag_russia")] = true,
	[GetHashKey("prop_flag_russia_s")] = true,
	[GetHashKey("prop_flag_s")] = true,
	[GetHashKey("ch2_03c_props_rrlwindmill_lod")] = true,
	[GetHashKey("prop_flag_sa")] = true,
	[GetHashKey("prop_flag_sapd")] = true,
	[GetHashKey("prop_flag_sapd_s")] = true,
	[GetHashKey("prop_flag_sa_s")] = true,
	[GetHashKey("prop_flag_scotland")] = true,
	[GetHashKey("prop_flag_scotland_s")] = true,
	[GetHashKey("prop_flag_sheriff")] = true,
	[GetHashKey("prop_flag_sheriff_s")] = true,
	[GetHashKey("prop_flag_uk")] = true,
	[GetHashKey("prop_yacht_lounger")] = true,
	[GetHashKey("prop_yacht_seat_01")] = true,
	[GetHashKey("prop_yacht_seat_02")] = true,
	[GetHashKey("prop_yacht_seat_03")] = true,
	[GetHashKey("marina_xr_rocks_02")] = true,
	[GetHashKey("marina_xr_rocks_03")] = true,
	[GetHashKey("prop_test_rocks01")] = true,
	[GetHashKey("prop_test_rocks02")] = true,
	[GetHashKey("prop_test_rocks03")] = true,
	[GetHashKey("prop_test_rocks04")] = true,
	[GetHashKey("marina_xr_rocks_04")] = true,
	[GetHashKey("marina_xr_rocks_05")] = true,
	[GetHashKey("marina_xr_rocks_06")] = true,
	[GetHashKey("prop_yacht_table_01")] = true,
	[GetHashKey("csx_searocks_02")] = true,
	[GetHashKey("csx_searocks_03")] = true,
	[GetHashKey("csx_searocks_04")] = true,
	[GetHashKey("csx_searocks_05")] = true,
	[GetHashKey("csx_searocks_06")] = true,
	[GetHashKey("p_yacht_chair_01_s")] = true,
	[GetHashKey("p_yacht_sofa_01_s")] = true,
	[GetHashKey("prop_yacht_table_02")] = true,
	[GetHashKey("csx_coastboulder_00")] = true,
	[GetHashKey("csx_coastboulder_01")] = true,
	[GetHashKey("csx_coastboulder_02")] = true,
	[GetHashKey("csx_coastboulder_03")] = true,
	[GetHashKey("csx_coastboulder_04")] = true,
	[GetHashKey("csx_coastboulder_05")] = true,
	[GetHashKey("csx_coastboulder_06")] = true,
	[GetHashKey("csx_coastboulder_07")] = true,
	[GetHashKey("csx_coastrok1")] = true,
	[GetHashKey("csx_coastrok2")] = true,
	[GetHashKey("csx_coastrok3")] = true,
	[GetHashKey("csx_coastrok4")] = true,
	[GetHashKey("csx_coastsmalrock_01")] = true,
	[GetHashKey("csx_coastsmalrock_02")] = true,
	[GetHashKey("csx_coastsmalrock_03")] = true,
	[GetHashKey("csx_coastsmalrock_04")] = true,
	[GetHashKey("csx_coastsmalrock_05")] = true,
	[GetHashKey("prop_yacht_table_03")] = true,
	[GetHashKey("prop_flag_uk_s")] = true,
	[GetHashKey("prop_flag_us")] = true,
	[GetHashKey("prop_flag_usboat")] = true,
	[GetHashKey("prop_flag_us_r")] = true,
	[GetHashKey("prop_flag_us_s")] = true,
	[GetHashKey("p_gasmask_s")] = true,
	[GetHashKey("prop_flamingo")] = true,
	[GetHashKey("stt_prop_stunt_soccer_ball")] = true,
	[GetHashKey("prop_rock_4_big2")] = true,
	[GetHashKey("p_crahsed_heli_s")] = true,
	[GetHashKey("stt_prop_c4_stack")] = true,
	[GetHashKey("stt_prop_corner_sign_01")] = true,
	[GetHashKey("stt_prop_corner_sign_02")] = true,
	[GetHashKey("stt_prop_corner_sign_03")] = true,
	[GetHashKey("stt_prop_corner_sign_04")] = true,
	[GetHashKey("stt_prop_corner_sign_05")] = true,
	[GetHashKey("stt_prop_corner_sign_06")] = true,
	[GetHashKey("stt_prop_corner_sign_07")] = true,
	[GetHashKey("stt_prop_corner_sign_08")] = true,
	[GetHashKey("stt_prop_corner_sign_09")] = true,
	[GetHashKey("stt_prop_corner_sign_10")] = true,
	[GetHashKey("stt_prop_corner_sign_11")] = true,
	[GetHashKey("stt_prop_corner_sign_12")] = true,
	[GetHashKey("stt_prop_corner_sign_13")] = true,
	[GetHashKey("stt_prop_corner_sign_14")] = true,
	[GetHashKey("stt_prop_flagpole_1a")] = true,
	[GetHashKey("stt_prop_flagpole_1b")] = true,
	[GetHashKey("stt_prop_flagpole_1c")] = true,
	[GetHashKey("stt_prop_flagpole_1d")] = true,
	[GetHashKey("stt_prop_flagpole_1e")] = true,
	[GetHashKey("stt_prop_flagpole_1f")] = true,
	[GetHashKey("stt_prop_flagpole_2a")] = true,
	[GetHashKey("stt_prop_flagpole_2b")] = true,
	[GetHashKey("stt_prop_flagpole_2c")] = true,
	[GetHashKey("stt_prop_flagpole_2d")] = true,
	[GetHashKey("stt_prop_flagpole_2e")] = true,
	[GetHashKey("stt_prop_flagpole_2f")] = true,
	[GetHashKey("stt_prop_hoop_constraction_01a")] = true,
	[GetHashKey("stt_prop_hoop_small_01")] = true,
	[GetHashKey("stt_prop_hoop_tyre_01a")] = true,
	[GetHashKey("stt_prop_lives_bottle")] = true,
	[GetHashKey("stt_prop_race_gantry_01")] = true,
	[GetHashKey("stt_prop_race_start_line_01")] = true,
	[GetHashKey("stt_prop_race_start_line_01b")] = true,
	[GetHashKey("stt_prop_race_start_line_02")] = true,
	[GetHashKey("stt_prop_race_start_line_02b")] = true,
	[GetHashKey("stt_prop_race_start_line_03")] = true,
	[GetHashKey("stt_prop_race_start_line_03b")] = true,
	[GetHashKey("stt_prop_race_tannoy")] = true,
	[GetHashKey("stt_prop_ramp_adj_flip_m")] = true,
	[GetHashKey("stt_prop_ramp_adj_flip_mb")] = true,
	[GetHashKey("stt_prop_ramp_adj_flip_s")] = true,
	[GetHashKey("stt_prop_ramp_adj_flip_sb")] = true,
	[GetHashKey("stt_prop_ramp_adj_hloop")] = true,
	[GetHashKey("stt_prop_ramp_adj_loop")] = true,
	[GetHashKey("stt_prop_ramp_jump_l")] = true,
	[GetHashKey("stt_prop_ramp_jump_m")] = true,
	[GetHashKey("stt_prop_ramp_jump_s")] = true,
	[GetHashKey("stt_prop_ramp_jump_xl")] = true,
	[GetHashKey("stt_prop_ramp_jump_xs")] = true,
	[GetHashKey("stt_prop_ramp_jump_xxl")] = true,
	[GetHashKey("stt_prop_ramp_multi_loop_rb")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l_l")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l_m")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l_s")] = true,
	[GetHashKey("stt_prop_ramp_spiral_l_xxl")] = true,
	[GetHashKey("stt_prop_ramp_spiral_m")] = true,
	[GetHashKey("stt_prop_ramp_spiral_s")] = true,
	[GetHashKey("stt_prop_ramp_spiral_xxl")] = true,
	[GetHashKey("stt_prop_sign_circuit_01")] = true,
	[GetHashKey("stt_prop_sign_circuit_02")] = true,
	[GetHashKey("stt_prop_sign_circuit_03")] = true,
	[GetHashKey("stt_prop_sign_circuit_04")] = true,
	[GetHashKey("stt_prop_sign_circuit_05")] = true,
	[GetHashKey("stt_prop_sign_circuit_06")] = true,
	[GetHashKey("stt_prop_sign_circuit_07")] = true,
	[GetHashKey("stt_prop_sign_circuit_08")] = true,
	[GetHashKey("stt_prop_sign_circuit_09")] = true,
	[GetHashKey("stt_prop_sign_circuit_10")] = true,
	[GetHashKey("stt_prop_sign_circuit_11")] = true,
	[GetHashKey("stt_prop_sign_circuit_11b")] = true,
	[GetHashKey("stt_prop_sign_circuit_12")] = true,
	[GetHashKey("stt_prop_sign_circuit_13")] = true,
	[GetHashKey("stt_prop_sign_circuit_13b")] = true,
	[GetHashKey("stt_prop_sign_circuit_14")] = true,
	[GetHashKey("stt_prop_sign_circuit_14b")] = true,
	[GetHashKey("stt_prop_sign_circuit_15")] = true,
	[GetHashKey("stt_prop_slow_down")] = true,
	[GetHashKey("stt_prop_speakerstack_01a")] = true,
	[GetHashKey("stt_prop_startline_gantry")] = true,
	[GetHashKey("stt_prop_stunt_bblock_huge_01")] = true,
	[GetHashKey("stt_prop_stunt_bblock_huge_02")] = true,
	[GetHashKey("stt_prop_stunt_bblock_huge_03")] = true,
	[GetHashKey("stt_prop_stunt_bblock_huge_04")] = true,
	[GetHashKey("stt_prop_stunt_bblock_huge_05")] = true,
	[GetHashKey("stt_prop_stunt_bblock_hump_01")] = true,
	[GetHashKey("stt_prop_stunt_bblock_hump_02")] = true,
	[GetHashKey("stt_prop_stunt_bblock_lrg1")] = true,
	[GetHashKey("stt_prop_stunt_bblock_lrg2")] = true,
	[GetHashKey("stt_prop_stunt_bblock_lrg3")] = true,
	[GetHashKey("stt_prop_stunt_bblock_mdm1")] = true,
	[GetHashKey("stt_prop_stunt_bblock_mdm2")] = true,
	[GetHashKey("stt_prop_stunt_bblock_mdm3")] = true,
	[GetHashKey("stt_prop_stunt_bblock_qp")] = true,
	[GetHashKey("stt_prop_stunt_bblock_qp2")] = true,
	[GetHashKey("stt_prop_stunt_bblock_qp3")] = true,
	[GetHashKey("stt_prop_stunt_bblock_sml1")] = true,
	[GetHashKey("stt_prop_stunt_bblock_sml2")] = true,
	[GetHashKey("stt_prop_stunt_bblock_sml3")] = true,
	[GetHashKey("stt_prop_stunt_bblock_xl1")] = true,
	[GetHashKey("stt_prop_stunt_bblock_xl2")] = true,
	[GetHashKey("stt_prop_stunt_bblock_xl3")] = true,
	[GetHashKey("stt_prop_stunt_bowling_ball")] = true,
	[GetHashKey("stt_prop_stunt_bowling_pin")] = true,
	[GetHashKey("stt_prop_stunt_bowlpin_stand")] = true,
	[GetHashKey("stt_prop_stunt_domino")] = true,
	[GetHashKey("stt_prop_stunt_jump15")] = true,
	[GetHashKey("stt_prop_stunt_jump30")] = true,
	[GetHashKey("stt_prop_stunt_jump45")] = true,
	[GetHashKey("stt_prop_stunt_jump_l")] = true,
	[GetHashKey("stt_prop_stunt_jump_lb")] = true,
	[GetHashKey("stt_prop_stunt_jump_loop")] = true,
	[GetHashKey("stt_prop_stunt_jump_m")] = true,
	[GetHashKey("stt_prop_stunt_jump_mb")] = true,
	[GetHashKey("stt_prop_stunt_jump_s")] = true,
	[GetHashKey("stt_prop_stunt_jump_sb")] = true,
	[GetHashKey("stt_prop_stunt_landing_zone_01")] = true,
	[GetHashKey("stt_prop_stunt_ramp")] = true,
	[GetHashKey("stt_prop_stunt_soccer_ball")] = true,
	[GetHashKey("stt_prop_stunt_soccer_goal")] = true,
	[GetHashKey("stt_prop_stunt_soccer_lball")] = true,
	[GetHashKey("stt_prop_stunt_soccer_sball")] = true,
	[GetHashKey("stt_prop_stunt_target")] = true,
	[GetHashKey("stt_prop_stunt_target_small")] = true,
	[GetHashKey("stt_prop_stunt_track_bumps")] = true,
	[GetHashKey("stt_prop_stunt_track_cutout")] = true,
	[GetHashKey("stt_prop_stunt_track_dwlink")] = true,
	[GetHashKey("stt_prop_stunt_track_dwlink_02")] = true,
	[GetHashKey("stt_prop_stunt_track_dwsh15")] = true,
	[GetHashKey("stt_prop_stunt_track_dwshort")] = true,
	[GetHashKey("stt_prop_stunt_track_dwslope15")] = true,
	[GetHashKey("stt_prop_stunt_track_dwslope30")] = true,
	[GetHashKey("stt_prop_stunt_track_dwslope45")] = true,
	[GetHashKey("stt_prop_stunt_track_dwturn")] = true,
	[GetHashKey("stt_prop_stunt_track_dwuturn")] = true,
	[GetHashKey("stt_prop_stunt_track_exshort")] = true,
	[GetHashKey("stt_prop_stunt_track_fork")] = true,
	[GetHashKey("stt_prop_stunt_track_funlng")] = true,
	[GetHashKey("stt_prop_stunt_track_funnel")] = true,
	[GetHashKey("stt_prop_stunt_track_hill")] = true,
	[GetHashKey("stt_prop_stunt_track_hill2")] = true,
	[GetHashKey("stt_prop_stunt_track_jump")] = true,
	[GetHashKey("stt_prop_stunt_track_link")] = true,
	[GetHashKey("stt_prop_stunt_track_otake")] = true,
	[GetHashKey("stt_prop_stunt_track_sh15")] = true,
	[GetHashKey("stt_prop_stunt_track_sh30")] = true,
	[GetHashKey("stt_prop_stunt_track_sh45")] = true,
	[GetHashKey("stt_prop_stunt_track_sh45_a")] = true,
	[GetHashKey("stt_prop_stunt_track_short")] = true,
	[GetHashKey("stt_prop_stunt_track_slope15")] = true,
	[GetHashKey("stt_prop_stunt_track_slope30")] = true,
	[GetHashKey("stt_prop_stunt_track_slope45")] = true,
	[GetHashKey("stt_prop_stunt_track_start")] = true,
	[GetHashKey("stt_prop_stunt_track_start_02")] = true,
	[GetHashKey("stt_prop_stunt_track_straight")] = true,
	[GetHashKey("stt_prop_stunt_track_straightice")] = true,
	[GetHashKey("stt_prop_stunt_track_st_01")] = true,
	[GetHashKey("stt_prop_stunt_track_st_02")] = true,
	[GetHashKey("stt_prop_stunt_track_turn")] = true,
	[GetHashKey("stt_prop_stunt_track_turnice")] = true,
	[GetHashKey("stt_prop_stunt_track_uturn")] = true,
	[GetHashKey("stt_prop_stunt_tube_crn")] = true,
	[GetHashKey("stt_prop_stunt_tube_crn2")] = true,
	[GetHashKey("stt_prop_stunt_tube_crn_15d")] = true,
	[GetHashKey("stt_prop_stunt_tube_crn_30d")] = true,
	[GetHashKey("stt_prop_stunt_tube_crn_5d")] = true,
	[GetHashKey("stt_prop_stunt_tube_cross")] = true,
	[GetHashKey("stt_prop_stunt_tube_end")] = true,
	[GetHashKey("stt_prop_stunt_tube_ent")] = true,
	[GetHashKey("stt_prop_stunt_tube_fn_01")] = true,
	[GetHashKey("stt_prop_stunt_tube_fn_02")] = true,
	[GetHashKey("stt_prop_stunt_tube_fn_03")] = true,
	[GetHashKey("stt_prop_stunt_tube_fn_04")] = true,
	[GetHashKey("stt_prop_stunt_tube_fn_05")] = true,
	[GetHashKey("stt_prop_stunt_tube_fork")] = true,
	[GetHashKey("stt_prop_stunt_tube_gap_01")] = true,
	[GetHashKey("stt_prop_stunt_tube_gap_02")] = true,
	[GetHashKey("stt_prop_stunt_tube_gap_03")] = true,
	[GetHashKey("stt_prop_stunt_tube_hg")] = true,
	[GetHashKey("stt_prop_stunt_tube_jmp")] = true,
	[GetHashKey("stt_prop_stunt_tube_jmp2")] = true,
	[GetHashKey("stt_prop_stunt_tube_l")] = true,
	[GetHashKey("stt_prop_stunt_tube_m")] = true,
	[GetHashKey("stt_prop_stunt_tube_qg")] = true,
	[GetHashKey("stt_prop_stunt_tube_s")] = true,
	[GetHashKey("stt_prop_stunt_tube_speed")] = true,
	[GetHashKey("stt_prop_stunt_tube_speeda")] = true,
	[GetHashKey("stt_prop_stunt_tube_speedb")] = true,
	[GetHashKey("stt_prop_stunt_tube_xs")] = true,
	[GetHashKey("stt_prop_stunt_tube_xxs")] = true,
	[GetHashKey("stt_prop_stunt_wideramp")] = true,
	[GetHashKey("stt_prop_track_bend2_bar_l")] = true,
	[GetHashKey("stt_prop_track_bend2_bar_l_b")] = true,
	[GetHashKey("stt_prop_track_bend2_l")] = true,
	[GetHashKey("stt_prop_track_bend2_l_b")] = true,
	[GetHashKey("stt_prop_track_bend_15d")] = true,
	[GetHashKey("stt_prop_track_bend_15d_bar")] = true,
	[GetHashKey("stt_prop_track_bend_180d")] = true,
	[GetHashKey("stt_prop_track_bend_180d_bar")] = true,
	[GetHashKey("stt_prop_track_bend_30d")] = true,
	[GetHashKey("stt_prop_track_bend_30d_bar")] = true,
	[GetHashKey("stt_prop_track_bend_5d")] = true,
	[GetHashKey("stt_prop_track_bend_5d_bar")] = true,
	[GetHashKey("stt_prop_track_bend_bar_l")] = true,
	[GetHashKey("stt_prop_track_bend_bar_l_b")] = true,
	[GetHashKey("stt_prop_track_bend_bar_m")] = true,
	[GetHashKey("stt_prop_track_bend_l")] = true,
	[GetHashKey("stt_prop_track_bend_l_b")] = true,
	[GetHashKey("stt_prop_track_bend_m")] = true,
	[GetHashKey("stt_prop_track_block_01")] = true,
	[GetHashKey("stt_prop_track_block_02")] = true,
	[GetHashKey("stt_prop_track_block_03")] = true,
	[GetHashKey("stt_prop_track_chicane_l")] = true,
	[GetHashKey("stt_prop_track_chicane_l_02")] = true,
	[GetHashKey("stt_prop_track_chicane_r")] = true,
	[GetHashKey("stt_prop_track_chicane_r_02")] = true,
	[GetHashKey("stt_prop_track_cross")] = true,
	[GetHashKey("stt_prop_track_cross_bar")] = true,
	[GetHashKey("stt_prop_track_fork")] = true,
	[GetHashKey("stt_prop_track_fork_bar")] = true,
	[GetHashKey("stt_prop_track_funnel")] = true,
	[GetHashKey("stt_prop_track_funnel_ads_01a")] = true,
	[GetHashKey("stt_prop_track_funnel_ads_01b")] = true,
	[GetHashKey("stt_prop_track_funnel_ads_01c")] = true,
	[GetHashKey("stt_prop_track_jump_01a")] = true,
	[GetHashKey("stt_prop_track_jump_01b")] = true,
	[GetHashKey("stt_prop_track_jump_01c")] = true,
	[GetHashKey("stt_prop_track_jump_02a")] = true,
	[GetHashKey("stt_prop_track_jump_02b")] = true,
	[GetHashKey("stt_prop_track_jump_02c")] = true,
	[GetHashKey("stt_prop_track_link")] = true,
	[GetHashKey("stt_prop_track_slowdown")] = true,
	[GetHashKey("stt_prop_track_slowdown_t1")] = true,
	[GetHashKey("stt_prop_track_slowdown_t2")] = true,
	[GetHashKey("stt_prop_track_speedup")] = true,
	[GetHashKey("stt_prop_track_speedup_t1")] = true,
	[GetHashKey("stt_prop_track_speedup_t2")] = true,
	[GetHashKey("stt_prop_track_start")] = true,
	[GetHashKey("stt_prop_track_start_02")] = true,
	[GetHashKey("stt_prop_track_stop_sign")] = true,
	[GetHashKey("stt_prop_track_straight_bar_l")] = true,
	[GetHashKey("stt_prop_track_straight_bar_m")] = true,
	[GetHashKey("stt_prop_track_straight_bar_s")] = true,
	[GetHashKey("stt_prop_track_straight_l")] = true,
	[GetHashKey("stt_prop_track_straight_lm")] = true,
	[GetHashKey("stt_prop_track_straight_lm_bar")] = true,
	[GetHashKey("stt_prop_track_straight_m")] = true,
	[GetHashKey("stt_prop_track_straight_s")] = true,
	[GetHashKey("stt_prop_track_tube_01")] = true,
	[GetHashKey("stt_prop_track_tube_02")] = true,
	[GetHashKey("stt_prop_tyre_wall_01")] = true,
	[GetHashKey("stt_prop_tyre_wall_010")] = true,
	[GetHashKey("stt_prop_tyre_wall_011")] = true,
	[GetHashKey("stt_prop_tyre_wall_012")] = true,
	[GetHashKey("stt_prop_tyre_wall_013")] = true,
	[GetHashKey("stt_prop_tyre_wall_014")] = true,
	[GetHashKey("stt_prop_tyre_wall_015")] = true,
	[GetHashKey("stt_prop_tyre_wall_02")] = true,
	[GetHashKey("stt_prop_tyre_wall_03")] = true,
	[GetHashKey("stt_prop_tyre_wall_04")] = true,
	[GetHashKey("stt_prop_tyre_wall_05")] = true,
	[GetHashKey("stt_prop_tyre_wall_06")] = true,
	[GetHashKey("stt_prop_tyre_wall_07")] = true,
	[GetHashKey("stt_prop_tyre_wall_08")] = true,
	[GetHashKey("stt_prop_tyre_wall_09")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l010")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l012")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l013")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l014")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l015")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l018")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l019")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l020")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l04")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l05")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l06")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l07")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l08")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l1")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l16")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l17")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l2")] = true,
	[GetHashKey("stt_prop_tyre_wall_0l3")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r010")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r011")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r012")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r013")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r014")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r015")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r016")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r017")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r018")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r019")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r04")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r05")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r06")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r07")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r08")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r09")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r1")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r2")] = true,
	[GetHashKey("stt_prop_tyre_wall_0r3")] = true,
	[GetHashKey("stt_prop_wallride_01")] = true,
	[GetHashKey("stt_prop_wallride_01b")] = true,
	[GetHashKey("stt_prop_wallride_02")] = true,
	[GetHashKey("stt_prop_wallride_02b")] = true,
	[GetHashKey("stt_prop_wallride_04")] = true,
	[GetHashKey("stt_prop_wallride_05")] = true,
	[GetHashKey("stt_prop_wallride_05b")] = true,
	[GetHashKey("stt_prop_wallride_45l")] = true,
	[GetHashKey("stt_prop_wallride_45la")] = true,
	[GetHashKey("stt_prop_wallride_45r")] = true,
	[GetHashKey("stt_prop_wallride_45ra")] = true,
	[GetHashKey("stt_prop_wallride_90l")] = true,
	[GetHashKey("stt_prop_wallride_90lb")] = true,
	[GetHashKey("stt_prop_wallride_90r")] = true,
	[GetHashKey("stt_prop_wallride_90rb")] = true,
	[GetHashKey("prop_fnclink_05crnr1")] = true,
	[GetHashKey("xs_prop_hamburgher_wl")] = true,
	[GetHashKey("xs_prop_plastic_bottle_wl")] = true,
	[GetHashKey("stt_prop_stunt_track_dwslope15")] = true,
	[GetHashKey("stt_prop_stunt_track_dwslope30")] = true,
	[GetHashKey("stt_prop_stunt_track_dwslope45")] = true,
	[GetHashKey("stt_prop_stunt_track_dwturn")] = true,
	[GetHashKey("stt_prop_stunt_track_fork")] = true,
	[GetHashKey("stt_prop_stunt_track_dwuturn")] = true,
	[GetHashKey("stt_prop_stunt_track_exshort")] = true,
	[GetHashKey("stt_prop_stunt_track_hill")] = true,
	[GetHashKey("stt_prop_stunt_track_funnel")] = true,
	[GetHashKey("stt_prop_stunt_track_funlng")] = true,
}


vehConfig = {
    blacklist = {
        [GetHashKey("cargoplane")] = true,
        [GetHashKey("jet")] = true,
        [GetHashKey("tug")] = true,
        [GetHashKey("bus")] = true,
        [GetHashKey("dump")] = true,
        [GetHashKey("blimp")] = true,
        [GetHashKey("lazer")] = true,
        [GetHashKey("tanker")] = true
    }
}

-- Domyślny czas do usunięcia pojazdów z listy | 15000 = 15 sekund
vehConfig.LoopTime = 15000

-- Domyślny czas do usunięcia pojazdów z listy (odstep czasowy między każdym pojazdem). | 5 = 5ms (PONIŻEJ 1SEK, POWYŻEJ 25SEK = CRASHH) |
vehConfig.TimeBetween = 5

pedConfig = {
    blacklist = {
        [GetHashKey("a_m_o_acult_01")] = true,
        [GetHashKey("a_f_m_fatwhite_01")] = true,
        [GetHashKey("s_m_m_autoshop_01")] = true,
        [GetHashKey("a_m_y_surfer_01")] = true,
        [GetHashKey("s_m_y_swat_01")] = true,
        [GetHashKey("ig_wade")] = true,
        [GetHashKey("a_c_deer")] = true,
        [GetHashKey("a_c_boar")] = true,
        [GetHashKey("a_c_killerwhale")] = true,
        [GetHashKey("a_c_sharktiger")] = true,
        [GetHashKey("csb_stripper_01")] = true,
        [GetHashKey("A_C_MtLion")] = true,
        [GetHashKey("mp_f_cocaine_01")] = true,
        [GetHashKey("ig_claypain")] = true,
        [GetHashKey("u_m_m_jesus_01")] = true,
        [GetHashKey("S_M_Y_MARINE_01")] = true,
        [GetHashKey("s_m_m_movalien_01")] = true,
        [GetHashKey("A_C_Rottweiler")] = true,
        [GetHashKey("A_C_Husky")] = true,
        [GetHashKey("S_M_Y_Marine_03")] = true,
        [GetHashKey("CS_MovPremMale")] = true,
        [GetHashKey("G_M_Y_Lost_03")] = true,
        [GetHashKey("G_M_M_ChiCold_01")] = true,
    }
}

-- Domyślny czas do usunięcia pedów z listy | 15000 = 15 sekund
pedConfig.LoopTime = 15000

-- Domyślny czas do usunięcia pedów z listy (odstep czasowy między każdym pedem). | 5 = 5ms  | (PONIŻEJ 1SEK, POWYŻEJ 25SEK = CRASHH) |
pedConfig.TimeBetween = 5


-- cr https://gtahash.ru/

-- { 'esx_drugs:startHarvestWeed', 'esx_drugs:startTransformWeed', 'esx_drugs:startHarvestCoke', 'esx_drugs:startTransformCoke', 'esx_drugs:startHarvestOpium', 'esx_drugs:startTransformOpium', 'esx_policejob:handcuff', 'esx_ambulancejob:revive', 'esx_jailer:sendToJail', "gcPhone:_internalAddMessageLRAC", }